version: 2

jobs:
  docker_push:
    # Build app container and push it to the GCR registry
    # Note: we want to build and push an image with tags based on both
    # the Git commit hash AND the branch name. This way, we can refer to
    # images by commit (which is immutable) or branch name (which
    # dynamically tracks the latest build for each branch).
    docker:
      - image: bayesimpact/circleci:latest
    working_directory: /go/src/github.com/obedtandadjaja/project-k-react
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with GCR
          command: |
            echo "${GCR_DOCKER_REGISTRY_PASSWORD}" | docker login -u _json_key --password-stdin https://gcr.io
      - run:
          name: Build app image
          command: |
            docker build --rm=false \
            -t gcr.io/${GCP_PROJECT_ID}/project-k-react:${CIRCLE_SHA1} \
            -t gcr.io/${GCP_PROJECT_ID}/project-k-react:${CIRCLE_BRANCH} \
            -f ./Dockerfile .
      - run:
          name: Push app image
          command: |
            docker push gcr.io/${GCP_PROJECT_ID}/project-k-react:${CIRCLE_SHA1}
            docker push gcr.io/${GCP_PROJECT_ID}/project-k-react:${CIRCLE_BRANCH}

  kubernetes_deploy:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: /go/src/github.com/obedtandadjaja/project-k-react
    steps:
      - checkout
      - run:
          name: Deploy the current commit on this branch to the GKE cluster
          command: |
            gcloud components install kubectl
            echo "${GKE_CD_SERVICE_ACCOUNT_KEY}" > .key.json
            gcloud auth activate-service-account --key-file .key.json
            gcloud config set compute/zone "${GKE_ZONE}"
            gcloud config set project "${GCP_PROJECT_ID}"
            gcloud container clusters get-credentials "${GKE_CLUSTER}" --zone "${GKE_ZONE}"

            DEPLOYMENT_SUFFIX="-stg"

            kubectl apply -f k8/config-env-stage.yaml
            kubectl apply -f k8/service.yaml

            template=`cat "k8/deployment.yaml" | sed "s/{{IMAGE_TAG}}/$CIRCLE_SHA1/g" | sed "s/{{ENV}}/$DEPLOYMENT_SUFFIX/g"`
            echo "$template" | kubectl apply -f -

# all workflows are only valid on master
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - docker_push:
          filters:
            branches:
              only:
                - master
      - kubernetes_deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - docker_push
