apiVersion: v1
kind: Service
metadata:
  name: project-k-react
  labels:
    app: project-k-react
spec:
  selector:
    app: project-k-react
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
